<?php
echo $this->headScript()
            ->appendFile('//code.jquery.com/jquery-1.12.4.js')
            ->appendFile('https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js');
echo $this->headLink()->appendStylesheet('https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css');
?>
<script>
$(document).ready(function() {
    $('#regtable').DataTable( {
        "ajax":"/events/ajax/reg/<?= $this->eventId ?>",
        "aaSorting" : [[0, 'desc']],
        "pageLength" : 5
    } );
} );
</script>
<style>
table.dataTable thead .sorting,
table.dataTable thead .sorting_asc,
table.dataTable thead .sorting_desc {
    background : none;
}
</style>
<div class="col-lg-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Registration Information for Event ID <?= $this->eventId ?></h2>
        </div>
        <div class="panel-body">
        <table id="regtable" class="display" cellspacing="0" width="100%">
            <tr><thead><th>Reg Date</th><th>First</th><th>Last</th><th>Attendees</th></thead></tr>
        </table>
        <hr />
        </div>
    </div>
</div>

