<!-- //*** PSR7BRIDGE LAB:: get the default locale using the PHP Locale class -->
<?php $locale = Locale::getDefault(); ?>
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default" style="height:500px;">

            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Messages Sent') ?></h3>
            </div>
            <div class="panel-body">
                <?php if (isset($this->sentMessages) && count($this->sentMessages)) : ?>
                    <table width="100%">
                    <?php foreach ($this->sentMessages as $message) : ?>
                        <!-- //*** PSR7BRIDGE LAB: format the date using the "dateFormat()" view helper using the locale given -->
                        <tr>
                            <th width="30%"><?= $message->getToEmail(); ?></th>
                            <!-- //*** I18N LAB: use "dateFormat()" here -->
                            <td width="30%"><?php echo $this->dateFormat(new DateTime($message->getDateTime()), \IntlDateFormatter::LONG,\IntlDateFormatter::NONE); ?></td>
                            <td width="60%"><?= $message->getMessage(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                <?php else : ?>
                    <br>None
                <?php endif; ?>
            </div>

            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Messages Received') ?></h3>
            </div>
            <div class="panel-body">
                <?php if (isset($this->receivedMessages) && count($this->receivedMessages)) : ?>
                    <table width="100%">
                    <?php foreach ($this->receivedMessages as $message) : ?>
                        <!-- //*** PSR7BRIDGE LAB:: format the date using the "dateFormat()" view helper using the locale given -->
                        <tr>
                            <th width="30%"><?= $message->getFromEmail(); ?></th>
                            <!-- //*** I18N LAB: use "dateFormat()" here -->
                            <td width="30%"><?php echo $this->dateFormat(new DateTime($message->getDateTime()), \IntlDateFormatter::LONG,\IntlDateFormatter::NONE); ?></td>
                            <td width="60%"><?= $message->getMessage(); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </table>
                <?php else : ?>
                    <br>None
                <?php endif; ?>
            </div>

        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default" style="height:500px;">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Send New Message') ?></h3>
            </div>
            <div class="panel-body">
                <?php $this->sendForm->setAttributes(['action' => $this->url('messages', ['action' => 'send'])]); ?>
                <?php $this->sendForm->prepare(); ?>
                <?= $this->form()->openTag($this->sendForm); ?>
                <dt><?= $this->formLabel($this->sendForm->get('fromEmail')); ?></dt>
                <dd><?= $this->formEmail($this->sendForm->get('fromEmail')); ?><?= $this->formElementErrors($this->sendForm->get('fromEmail')); ?></dd>
                <dt><?= $this->formLabel($this->sendForm->get('toEmail')); ?></dt>
                <dd><?= $this->formEmail($this->sendForm->get('toEmail')); ?><?= $this->formElementErrors($this->sendForm->get('toEmail')); ?></dd>
                <dt><?= $this->formLabel($this->sendForm->get('message')); ?></dt>
                <dd><?= $this->formTextarea($this->sendForm->get('message')); ?><?= $this->formElementErrors($this->sendForm->get('message')); ?></dd>
                <p><span class="btn btn-success"><?= $this->formSubmit($this->sendForm->get('submit')); ?></span></p>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        Status: <?php echo $this->status; ?>
        <br>Locale: <?php echo $locale; ?>
    </div>
</div>
