<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Events</h2>
        </div>
        <div class="panel-body">
            <h4>Sign Up Form</h4>
            <p><a class="btn btn-block btn-success btn-large" href="<?= $this->url('doctrine/signup'); ?>">Signup &raquo;</a></p>
            <h4>Admin Area</h4>
            <p><a class="btn btn-block btn-primary btn-large" href="<?= $this->url('doctrine/admin'); ?>">Admin &raquo;</a></p>
        </div>
    </div>
</div>

