<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Guestbook')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">&nbsp;Guestbook
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <!-- set role and acl to navigation -->
                    <?php
                        $user = NULL;
                        if ($this->authService) {
                            $user = $this->authService->getIdentity();
                        }
                        if (isset($this->acl)) {
                            $this->navigation('default')->setAcl($this->acl);
                            $role = ($user) ? $user->getRole() : 'guest';
                            $this->navigation('default')->setRole($role);
                        }
                    ?>
                    <?= $this->navigation('default')->menu()->setUlClass('nav navbar-nav'); ?>
                    <div style="color:white;vertical-align:center;float:right;">
                        <br>&nbsp;&nbsp;
                        <?php if ($user) : ?>
                            <?= $user->getEmail() . ' [' . $user->getLocale() . ']'; ?>
                        <?php else : ?>
                            <?= 'guest [' . Locale::getDefault() . ']'; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
